### ISSUE TITLE
Develop a way to see if nise changes will break iqe-tests.

### ISSUE THREAD

**Issue by myersCody** [project-koku/nise#188]
## User Story
As a developer I want a way to test if nice changes will break the iqe-tests before merging a pr. 

## Assumptions
- Because IQE is using pinned versions and downloading from PyPI we probably need to merge the new code before it can be tested in this regard
- We can update our nise docs to say when you create a new version, change the pinned version of `koku-nise` in your local IQE and run tests to verify things don't break. 

## Acceptance Criteria

- [ ] A documented or *hopefully* automated way to test if nise changes will break the iqe tests

**Comment by nbon12** [comment]
Sprint Planning conversation:
Andrew: Do we pin versions?
Luke: Yes
Andrew: Is there a convenient way to change version in local test run?
Luke: You could, but the problem is you'd want to install an editable version of Nise locally so you could test it, I'm not sure if that's currently do-able, I'm sure there's a way.
Andrew: Let's say this has to happen after merge, the merge causes new pypi, the developer who made the change, changes the pin locally and warns Luke not to update. 
Luke: If there's a new version, whoever is doing that new version is welcome to change the version in IQE and tag it.
