### ISSUE TITLE
CLI args should use sub-commands to organize options.

### ISSUE THREAD

**Issue by blentz** [project-koku/nise#190]
As a nise user, I want the CLI args to use [sub-commands](https://docs.python.org/3.6/library/argparse.html#sub-commands) to organize arguments into logical groupings so that it is more clear which arguments are grouped together without needing to include extraneous information in the argument itself. (e.g. `--aws-s3-bucket-name` could be simplified to `--bucket-name` if it's grouped into an AWS-specific grouping.)

The goal here is to improve program flow by making it clearer which options match each cloud provider and reducing program complexity by leveraging existing features of `argparse` that automatically validate incoming CLI args. 

## Assumptions
- This is akin to a refactor of how the argument parser is setup
- Leverage existing abilities of argparse to achieve this 

## Acceptance Criteria
- [ ] Existing users of nise (QE) are aware of changes and any required changes on their part are made. 
- [ ] All functionality remains and tests pass.

**Comment by nbon12** [comment]
Sprint Planning Meeting Notes:
Brett: "It's basically refactoring how the argument parser is set up. It's self contained to [re-doing] the parser, there's a couple validation functions that would be able to go away because the validation would happen in argparse already. It shouldn't change anything downstream. 
Andrew: "it's purely a re-factor"

**Comment by blentz** [comment]
Moved: https://issues.redhat.com/browse/COST-114
